namespace FluidicsSDK.Base
{
    /// <summary>
    /// Errors generated by the valve
    /// </summary>
    public enum ValveErrors
    {
        Success = 0,
        UnauthorizedAccess,
        TimeoutDuringRead,
        TimeoutDuringWrite,
        ValvePositionMismatch,
        BadArgument,
        BadCommand,
        UndefinedPort
    }
}
