using System;

namespace LcmsNetPlugins.LabJack
{
    /// <summary>
    /// A class containing exceptions generated by the Labjack U12
    /// </summary>
    public class LabjackU12Exception : Exception
    {
        public LabjackU12Exception()
            : base()
        {
        }
        public LabjackU12Exception(string message)
            : base(message)
        {
        }
        public LabjackU12Exception(string message, Exception ex)
            : base(message, ex)
        {
        }
    }
}
