using System;

namespace LcmsNetPlugins.LabJackT7
{
    /// <summary>
    /// A class containing exceptions generated by the LabJack T7
    /// </summary>
    public class LabJackT7Exception : Exception
    {
        public LabJackT7Exception()
            : base()
        {
        }

        public LabJackT7Exception(string message)
            : base(message)
        {
        }

        public LabJackT7Exception(string message, Exception ex)
            : base(message, ex)
        {
        }
    }
}
