//*********************************************************************************************************
// Written by Christopher Walters for the US Department of Energy
// Pacific Northwest National Laboratory, Richland, WA
// Copyright 2009, Battelle Memorial Institute
// Created 1/7/2014
//
// Last modified 1/7/2014
//*********************************************************************************************************

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LcmsNet.Devices.ContactClosure
{
    /// <summary>
    /// A class containing exceptions generated by the Labjack U3
    /// </summary>
    public class classLabjackU3Exception : Exception
    {
        public classLabjackU3Exception()
            : base()
        {
        }
        public classLabjackU3Exception(string message)
            : base(message)
        {
        }
        public classLabjackU3Exception(string message, Exception ex)
            : base(message, ex)
        {
        }
    }
}
