//*********************************************************************************************************
// Written by Christopher Walters for the US Department of Energy
// Pacific Northwest National Laboratory, Richland, WA
// Copyright 2009, Battelle Memorial Institute
// Created 1/7/2014
//
//*********************************************************************************************************

using System;

namespace LcmsNetPlugins.LabJackU3
{
    /// <summary>
    /// A class containing exceptions generated by the Labjack U3
    /// </summary>
    public class LabjackU3Exception : Exception
    {
        public LabjackU3Exception()
            : base()
        {
        }
        public LabjackU3Exception(string message)
            : base(message)
        {
        }
        public LabjackU3Exception(string message, Exception ex)
            : base(message, ex)
        {
        }
    }
}
