using System;
using LcmsNetData.Data;

namespace LcmsNetData.Logging
{
    /// <summary>
    /// Class that encapsulates a message generated by a component.
    /// </summary>
    public class MessageLoggerArgs : EventArgs
    {
        /// <summary>
        /// Constructor that takes the error message.
        /// </summary>
        /// <param name="message">Error message</param>
        public MessageLoggerArgs(string message)
        {
            Message = message;
            Sample = null;
        }

        /// <summary>
        /// Constructor that takes the error message.
        /// </summary>
        /// <param name="message">Error message</param>
        /// <param name="sample"></param>
        public MessageLoggerArgs(string message, SampleDataBasic sample)
        {
            Message = message;
            Sample = sample;
        }

        /// <summary>
        /// Gets or sets the error message associated with the error.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the sample data associated with this method.
        /// </summary>
        public SampleDataBasic Sample { get; set; }
    }
}