using System;

namespace LabJackTSeries
{
    /// <summary>
    /// A class containing exceptions generated by the LabJack T-series device
    /// </summary>
    public class LabJackTException : Exception
    {
        public LabJackTException()
            : base()
        {
        }

        public LabJackTException(string message)
            : base(message)
        {
        }

        public LabJackTException(string message, Exception ex)
            : base(message, ex)
        {
        }
    }
}
