namespace LcmsNetPlugins.XcaliburLC
{
    internal enum EventName
    {
        Acquiring,
        DataFileCompleted,
        DevicesAreReady,
        DiskSpaceWarning,
        DownloadAbandoned,
        DownloadCompleted,
        DownLoadInitiated,
        ErrorMessage,
        InformationalMessage,
        MethodCheckFail,
        MethodCheckOK,
        NewData,
        Pause,
        ProgramError,
        QueuedNewSequence,
        Resume,
        RunEnded,
        SequenceChange,
        SequenceClosed,
        SequenceOpened,
        StartCmdSent,
        StartedProcessing,
        StateChange,
        VDStateChange,
        WarningMessage,
    }
}