using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LcmsNetDataClasses.Logging
{
    /// <summary>
    /// Class that encapsulates a message generated by a component.
    /// </summary>
    public class classMessageLoggerArgs : EventArgs
    {
        /// <summary>
        /// Constructor that takes the error message.
        /// </summary>
        /// <param name="message">Error message</param>
        public classMessageLoggerArgs(string message)
        {
            Message = message;
            Sample = null;
        }

        /// <summary>
        /// Constructor that takes the error message.
        /// </summary>
        /// <param name="message">Error message</param>
        public classMessageLoggerArgs(string message, classSampleData sample)
        {
            Message = message;
            Sample = sample;
        }

        /// <summary>
        /// Gets or sets the error message associated with the error.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the sample data associated with this method.
        /// </summary>
        public classSampleData Sample { get; set; }
    }
}